name: npm publish
on:
  push:
    branches:
      - main

jobs:
  publish-github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        node-version: [ 14 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
      - name: setup
        run: |
          git config --local user.email "shrine8263@yeah.net"
          git config --local user.name "samsara"
      - name: bump verison
        run: |
          npm version patch
      - name: publish github package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    runs-on: ubuntu-latest
    needs: [ publish-github ]
    strategy:
      matrix:
        node-version: [ 14 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: setup
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: bump verison
        run: |
          npm version patch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS }}
          branch: ${{ github.ref }}
          tags: true
      - name: publish npm package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM}}