name: test
on:
  pull_request:
    branches:
      - main

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.com
      - name: setup
        run: |
          yarn add webpack@4
      - name: unit
        run: yarn run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  e2e:
    needs: [ unit ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14 ]
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: |
          yarn add webpack@4
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve
          parallel: true
          spec: ./cypress/integration/webpack-module-graph/**/*"